//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eneca.SpacesManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eneca.SpacesManager.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADSK_Size_Area.
        /// </summary>
        public static string Area_ParName {
            get {
                return ResourceManager.GetString("Area_ParName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area has changed to.
        /// </summary>
        public static string AreaChanged {
            get {
                return ResourceManager.GetString("AreaChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create spaces.
        /// </summary>
        public static string CreateSpaces_Button {
            get {
                return ResourceManager.GetString("CreateSpaces_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete spaces.
        /// </summary>
        public static string DeleteSpaces_Button {
            get {
                return ResourceManager.GetString("DeleteSpaces_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial area.
        /// </summary>
        public static string InitialArea {
            get {
                return ResourceManager.GetString("InitialArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level from connection.
        /// </summary>
        public static string LevelLink {
            get {
                return ResourceManager.GetString("LevelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level in the model.
        /// </summary>
        public static string LevelModel {
            get {
                return ResourceManager.GetString("LevelModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LevelName {
            get {
                return ResourceManager.GetString("LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of spaces.
        /// </summary>
        public static string MonitorSpaces_Button {
            get {
                return ResourceManager.GetString("MonitorSpaces_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spaces created.
        /// </summary>
        public static string MSG_CreateSpacesP1 {
            get {
                return ResourceManager.GetString("MSG_CreateSpacesP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total rooms.
        /// </summary>
        public static string MSG_CreateSpacesP2 {
            get {
                return ResourceManager.GetString("MSG_CreateSpacesP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating shared parameter.
        /// </summary>
        public static string MSG_ErrorCreateSharedPar {
            get {
                return ResourceManager.GetString("MSG_ErrorCreateSharedPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find matching level for.
        /// </summary>
        public static string MSG_ErrorUnmatchingLevels {
            get {
                return ResourceManager.GetString("MSG_ErrorUnmatchingLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization in Installation Manager is required..
        /// </summary>
        public static string MSG_Install {
            get {
                return ResourceManager.GetString("MSG_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of remote spaces.
        /// </summary>
        public static string MSG_RemoteSpaces {
            get {
                return ResourceManager.GetString("MSG_RemoteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectet path for new Shared Parameters File..
        /// </summary>
        public static string MSG_SelectPath {
            get {
                return ResourceManager.GetString("MSG_SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required parameters did not found. Would you like to add it in project?.
        /// </summary>
        public static string MSG_SharedParamsNotFound {
            get {
                return ResourceManager.GetString("MSG_SharedParamsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eneca - Spaces Manager.
        /// </summary>
        public static string MSG_Title {
            get {
                return ResourceManager.GetString("MSG_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MSG_TitleError {
            get {
                return ResourceManager.GetString("MSG_TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Shared Parameter File..
        /// </summary>
        public static string MSG_UnableToCreateSharFile {
            get {
                return ResourceManager.GetString("MSG_UnableToCreateSharFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete unallocated spaces.
        /// </summary>
        public static string ToolTip_DeleteSpaces {
            get {
                return ResourceManager.GetString("ToolTip_DeleteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an architectural model.
        /// </summary>
        public static string UI_ChooseFfile {
            get {
                return ResourceManager.GetString("UI_ChooseFfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms from linkend file.
        /// </summary>
        public static string UI_RoomsLinks {
            get {
                return ResourceManager.GetString("UI_RoomsLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select appropriate levels.
        /// </summary>
        public static string UI_СorrespondingLevel {
            get {
                return ResourceManager.GetString("UI_СorrespondingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сhoose.
        /// </summary>
        public static string Сhoose {
            get {
                return ResourceManager.GetString("Сhoose", resourceCulture);
            }
        }
    }
}
